baseURL = "https://jjd-cyber.github.io/"
languageCode = "en-us"
title = "Jjd-cyber"
theme = "glim-midnight"

[params]
    title = "Jjd-cyber"
    
    # These words will "animate" inside the box under your name
    phrases = ["Cybersecurity Professional", "Network Professional", "Linux Enthusiast"]
    
    links = [
        {name = "Github", url = "https://github.com/Jjd-cyber" newTab = true},
        {name = "LinkedIn", url = "https://www.linkedin.com/in/joshua-d-3a4715333/" newTab = true},
	{name = "Resume", url = "https://nationalcyberleague.org/" newTab = true},
        {name = "Projects", url = "/posts/"}
    ] 

    footer = "A site in progress"