baseURL = "https://jjd-cyber.github.io/"
languageCode = "en-us"
title = "Jjd-cyber"
theme = "glim-midnight"

[params]
    # This is the big text at the top
    title = "Jjd-cyber"
    
    # These words will "animate" inside the box under your name
    phrases = ["Cybersecurity", "Network Professional", "Linux Enthusiast"]
    
    # These are the buttons that will appear in the box
    links = [
        {name = "Github", url = "https://github.com/Jjd-cyber"},
        {name = "LinkedIn", url = "https://linkedin.com/in/yourprofile"},
        {name = "Projects", url = "/posts/"}
    ] 

    # If you want a footer
    footer = "Made by Jjd-cyber"